# Generated by Django 3.2 on 2021-05-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField(max_length=9, null=True)),
                ('aluminfo', models.TextField(max_length=250)),
                ('alumsurvey', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=20)),
                ('middlename', models.TextField(max_length=20)),
                ('lastname', models.TextField(max_length=20)),
                ('ext_name', models.TextField(max_length=10, null=True)),
                ('email', models.TextField(max_length=50, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('gradelevel', models.TextField(max_length=15)),
                ('studenttype', models.TextField(max_length=15)),
                ('gender', models.TextField(max_length=15)),
                ('dateofbirth', models.DateField()),
                ('placeofbirth', models.TextField(max_length=30)),
                ('province', models.TextField(max_length=15)),
                ('mobilenumber', models.BigIntegerField(max_length=20)),
                ('telephonenumber', models.BigIntegerField(max_length=20, null=True)),
                ('nationality', models.TextField(max_length=15)),
                ('religion', models.TextField(max_length=15)),
                ('address', models.TextField(max_length=15)),
                ('barangay', models.TextField(max_length=15)),
                ('city', models.TextField(max_length=15)),
                ('status', models.TextField(default='pending', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='educbackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField(max_length=9, null=True)),
                ('preschool', models.TextField(max_length=250, null=True)),
                ('gradeschool', models.TextField(max_length=250, null=True)),
                ('highschool', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fambackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField(max_length=9, null=True)),
                ('motherinfo', models.TextField(max_length=250, null=True)),
                ('fatherinfo', models.TextField(max_length=250, null=True)),
                ('siblingsinfo', models.TextField(max_length=250, null=True)),
                ('otherfaminfo', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='governmentid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField(max_length=9, null=True)),
                ('lrn_id', models.IntegerField(max_length=15)),
                ('esc_id', models.IntegerField(max_length=15)),
                ('qvr_id', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField(max_length=9, null=True)),
                ('healthsurvey', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='schoolsurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField(max_length=9, null=True)),
                ('surveyinfo', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfield', models.TextField(max_length=10)),
            ],
        ),
    ]
