# Generated by Django 3.2 on 2021-05-20 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_enrollment', '0002_alter_application_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 20, 15, 33, 18, 482733)),
        ),
    ]
