# Generated by Django 3.2 on 2021-05-20 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager_enrollment', '0003_alter_application_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
