# Generated by Django 3.2 on 2021-05-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_enrollment', '0004_alter_application_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(max_length=50),
        ),
    ]
