# Generated by Django 3.2 on 2021-05-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_enrollment', '0005_alter_application_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='enrollment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='mobilenumber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='telephonenumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='educbackground',
            name='enrollment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fambackground',
            name='enrollment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='governmentid',
            name='enrollment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='governmentid',
            name='esc_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='governmentid',
            name='lrn_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='governmentid',
            name='qvr_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='health',
            name='enrollment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schoolsurvey',
            name='enrollment_id',
            field=models.IntegerField(null=True),
        ),
    ]
