# Generated by Django 3.2 on 2021-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_enrollment', '0006_auto_20210521_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='governmentid',
        ),
        migrations.AddField(
            model_name='application',
            name='esc_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='lrn_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='qvr_id',
            field=models.IntegerField(null=True),
        ),
    ]
