# Generated by Django 3.2 on 2021-05-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_enrollment', '0007_auto_20210521_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schoolsurvey',
        ),
    ]
