# Generated by Django 3.2 on 2021-05-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_enrollment', '0008_delete_schoolsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='schoolsurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField(null=True)),
                ('surveyinfo', models.TextField(max_length=250, null=True)),
            ],
        ),
    ]
