# Generated by Django 3.2 on 2021-05-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_enrollment', '0009_schoolsurvey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alumni',
        ),
        migrations.DeleteModel(
            name='educbackground',
        ),
        migrations.DeleteModel(
            name='fambackground',
        ),
        migrations.DeleteModel(
            name='health',
        ),
        migrations.DeleteModel(
            name='schoolsurvey',
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='status',
            new_name='status_finance',
        ),
        migrations.AddField(
            model_name='application',
            name='status_guidance',
            field=models.TextField(default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='status_registrar',
            field=models.TextField(default='pending', max_length=15),
        ),
    ]
