# Generated by Django 3.2 on 2021-06-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_enrollment', '0010_auto_20210525_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrolled_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=20)),
                ('middlename', models.TextField(max_length=20)),
                ('lastname', models.TextField(max_length=20)),
                ('gradelevel', models.TextField(max_length=15)),
                ('section', models.TextField(max_length=15)),
            ],
        ),
    ]
