---
- name: Enabling specific services
  service:
    name: '{{ item }}'
    enabled: yes
  with_items:
    - cpuspeed
    - crond
    - iptables
    - irqbalance
    - kudzu
    - messagebus
    - network
    - readahead_early
    - smartd
    - sshd
    - syslog
    - rsyslog
    - rc-local
    - zabbix-agent
  ignore_errors: yes
