---
- name: Disabling repo
  shell: "yum update curl --disablerepo=epel -y"


- name: Yum clean all
  shell: "yum clean all"


- name: Updating packages
  shell: "yum update -y"

- name: Copying epel-release
  copy:
    src: epel-release-latest-7.noarch.rpm
    dest: /root/

- name: Installing epel-release
  shell: "rpm -Uvh /root/epel-release-latest-7.noarch.rpm"
  ignore_errors: yes

- name: Installing packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - wget
    - epel-release
    - pciutils
    - which
    - iptables
    - openssl-devel
    - openssl
    - gcc
    - net-snmp
    - net-snmp-utils
    - net-snmp-devel
    - pcre-devel
    - zlib-devel
    - apr
    - apr-devel
    - openssl-devel
    - gd-devel
    - gd
    - vim-enhanced
    - ntp
    - xinetd
    - make
    - iptables
    - sudo
    - cronie
    - elinks
    - perl
    - perl-CPAN
    - perl-YAML
    - zip
    - unzip
    - cmake
    - libaio*
    - nc
    - openssl-devel
    - python
    - libselinux-python
    - net-tools
    - git
    - lsof
    - telnet
  ignore_errors: yes