# Generated by Django 3.2 on 2021-06-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading_management', '0004_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='last_name',
            new_name='username',
        ),
    ]
