# Generated by Django 3.2 on 2021-06-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_management', '0005_rename_last_name_teachers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='preschool_grading',
            name='sub_performance_task',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
