# Generated by Django 3.2 on 2021-06-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_management', '0006_preschool_grading_sub_performance_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preschool_grading',
            name='sub_performance_task',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
