# Generated by Django 3.2 on 2021-06-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_management', '0007_alter_preschool_grading_sub_performance_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='section',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
