# Generated by Django 3.2 on 2021-07-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_management', '0010_students_raw_written_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='raw_performance_task',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
