# Generated by Django 3.2 on 2021-07-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_management', '0011_students_raw_performance_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sraw_performance_task',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
