# Generated by Django 3.2 on 2021-07-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_management', '0012_students_sraw_performance_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pt_multip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='ww_multip',
            field=models.IntegerField(default=0),
        ),
    ]
