# Generated by Django 3.2 on 2021-07-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_management', '0013_auto_20210801_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='pt_multip',
        ),
        migrations.RemoveField(
            model_name='students',
            name='ww_multip',
        ),
        migrations.AddField(
            model_name='teachers',
            name='pt_multip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachers',
            name='ww_multip',
            field=models.IntegerField(default=0),
        ),
    ]
