# Generated by Django 3.2 on 2021-07-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_management', '0015_auto_20210801_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='performance_task_grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='written_work_grade',
            field=models.FloatField(default=0),
        ),
    ]
