# Generated by Django 3.2 on 2021-08-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_management', '0016_auto_20210801_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='total_items_pt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='total_items_ww',
            field=models.FloatField(default=0),
        ),
    ]
