# Generated by Django 3.2 on 2021-06-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0002_auto_20210622_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='desciption',
            new_name='description',
        ),
    ]
