# Generated by Django 3.2 on 2021-06-29 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0004_alter_uploadfilemodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 19, 19, 23, 155825)),
        ),
    ]
