# Generated by Django 3.2 on 2021-06-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0005_alter_uploadfilemodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
