# Generated by Django 3.2 on 2021-07-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0007_alter_uploadfilemodel_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uploadfilemodel',
            unique_together={('title', 'file')},
        ),
    ]
