# Generated by Django 3.2 on 2021-07-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0008_alter_uploadfilemodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uploadfilemodel',
            unique_together=set(),
        ),
    ]
