# Generated by Django 3.2 on 2021-07-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0010_alter_uploadfilemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfilemodel',
            options={'verbose_name': 'UploadFile Permissions', 'verbose_name_plural': 'UploadFile Permissions'},
        ),
    ]
