# Generated by Django 3.2 on 2021-07-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0011_alter_uploadfilemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('file', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Download History',
                'verbose_name_plural': 'Download History',
            },
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
