# Generated by Django 3.2 on 2021-07-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0012_auto_20210707_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistorymodel',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
